In [85]:
import pandas as pd 
messages=pd.read_csv('SpamClassifier-master\smsspamcollection\SMSSpamCollection',sep='\t',names=["label","message"])

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\a4ana\AppData\Local\Temp\ipykernel_10508\3067040668.py:2: SyntaxWarning: invalid escape sequence '\s'
  messages=pd.read_csv('SpamClassifier-master\smsspamcollection\SMSSpamCollection',sep='\t',names=["label","message"])


In [86]:
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [87]:
import re 
import nltk
from nltk.corpus import stopwords

In [88]:
from nltk.stem import PorterStemmer

In [89]:
pr=PorterStemmer()

In [90]:
reviews=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[pr.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review=' '.join(review)
    reviews.append(review)

In [91]:
reviews

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

## Create a Bag of word


In [128]:
y=pd.get_dummies(messages['label']).astype(int)
y=y.iloc[:,0].values

In [129]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(reviews,y,test_size=0.2,random_state=0)



In [130]:
## Create a Bag of word
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [131]:
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [95]:
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=1000,formatter=dict(float=lambda x: "%.3f" % x))

In [132]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [97]:
cv.vocabulary_

{'go': np.int64(811),
 'point': np.int64(1612),
 'crazi': np.int64(447),
 'avail': np.int64(116),
 'bugi': np.int64(229),
 'great': np.int64(859),
 'world': np.int64(2434),
 'la': np.int64(1100),
 'cine': np.int64(344),
 'got': np.int64(850),
 'wat': np.int64(2335),
 'ok': np.int64(1480),
 'lar': np.int64(1113),
 'joke': np.int64(1056),
 'wif': np.int64(2400),
 'free': np.int64(717),
 'entri': np.int64(617),
 'wkli': np.int64(2424),
 'comp': np.int64(395),
 'win': np.int64(2405),
 'cup': np.int64(462),
 'final': np.int64(685),
 'st': np.int64(1958),
 'may': np.int64(1268),
 'text': np.int64(2093),
 'receiv': np.int64(1697),
 'question': np.int64(1666),
 'std': np.int64(1974),
 'txt': np.int64(2203),
 'rate': np.int64(1678),
 'appli': np.int64(80),
 'free entri': np.int64(722),
 'entri wkli': np.int64(619),
 'std txt': np.int64(1975),
 'txt rate': np.int64(2209),
 'rate appli': np.int64(1679),
 'dun': np.int64(572),
 'say': np.int64(1801),
 'earli': np.int64(581),
 'alreadi': np.int64(5

In [133]:
y

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1], shape=(5572,))

In [134]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [135]:
from sklearn.naive_bayes import MultinomialNB


In [136]:
spam =MultinomialNB()

In [137]:
spam.fit(X_train,y_train)

MultinomialNB()

In [138]:
y_pred=spam.predict(X_test)

In [139]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [140]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[149  11]
 [  5 950]]
0.9856502242152466


In [141]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.93      0.95       160
           1       0.99      0.99      0.99       955

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [145]:
## creat etfid model
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(reviews,y,test_size=0.2,random_state=20)

In [146]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [148]:
tf= TfidfVectorizer(max_features=2500,ngram_range=(1,2))

In [149]:
X_train=tf.fit_transform(X_train).toarray()
X_test=tf.transform(X_test).toarray()


In [150]:
tf.vocabulary_

{'lor': np.int64(1218),
 'wait': np.int64(2319),
 'ar': np.int64(83),
 'laugh': np.int64(1139),
 'realli': np.int64(1713),
 'talk': np.int64(2075),
 'dont': np.int64(563),
 'care': np.int64(296),
 'other': np.int64(1537),
 'feel': np.int64(684),
 'probabl': np.int64(1670),
 'dear': np.int64(508),
 'amp': np.int64(58),
 'best': np.int64(168),
 'friend': np.int64(750),
 'hey': np.int64(939),
 'ever': np.int64(640),
 'vote': np.int64(2313),
 'next': np.int64(1443),
 'gave': np.int64(776),
 'photo': np.int64(1584),
 'regist': np.int64(1730),
 'drive': np.int64(581),
 'ah': np.int64(34),
 'tmr': np.int64(2153),
 'wanna': np.int64(2331),
 'meet': np.int64(1307),
 'free': np.int64(729),
 'msg': np.int64(1392),
 'singl': np.int64(1910),
 'find': np.int64(697),
 'partner': np.int64(1555),
 'area': np.int64(86),
 'real': np.int64(1709),
 'peopl': np.int64(1564),
 'chat': np.int64(329),
 'send': np.int64(1848),
 'per': np.int64(1565),
 'free msg': np.int64(739),
 'send chat': np.int64(1850),
 'pe

In [151]:
from sklearn.naive_bayes import MultinomialNB
mb=MultinomialNB()

In [152]:
mb.fit(X_train,y_train)

MultinomialNB()

In [153]:
y_pred=mb.predict(X_test)

In [154]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))


[[138  25]
 [  1 951]]
0.9766816143497757


In [155]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.85      0.91       163
           1       0.97      1.00      0.99       952

    accuracy                           0.98      1115
   macro avg       0.98      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115

